## Cleaning on the Datasets will be performed in this Notebook

In [40]:
# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Load Data

In [41]:
# 2022-2023
hms_23 = pd.read_csv("../data/raw/2022-2023/HMS_2022-2023_PUBLIC_instchars.csv")

C:\Users\noahh\AppData\Local\Temp\ipykernel_13300\2745917235.py:2: DtypeWarning: Columns (11: gender_text, 37: black_other_text, 43: asian_other_text, 50: his_other_text, 56: st_tps, 63: st_otherdoc_text, 78: degree_other_text, 101: covid_clsformat_text, 105: enroll_text, 135: residenc_text, 186: sib_other_text, 203: alc_binge_othgen, 240: dx_bip_4_text, 248: dx_ax_6_text, 251: dx_ocd_3, 255: dx_ocd_6_text, 260: dx_trauma_4_text, 266: dx_neurodev_4_text, 270: dx_ea_4, 273: dx_ea_6_text, 276: dx_psy_3, 277: dx_psy_4, 278: dx_psy_5, 279: dx_psy_6, 282: dx_perso_1, 283: dx_perso_2, 287: dx_perso_6, 290: dx_perso_9, 291: dx_perso_10, 292: dx_perso_11, 293: dx_perso_12, 298: dx_sa_3, 299: dx_sa_2_text, 310: disab_1_9_text, 322: talk1_8_text, 412: stim_reason_text, 418: antidep_reason_text, 422: antipsy_reason_4, 423: antipsy_reason_5, 430: antianx_reason_text, 432: mood_reason_2, 434: mood_reason_4, 436: mood_reason_text, 440: slpmed_reason_4, 442: slpmed_reason_text, 448: othmed_reason_text, 455: meds_w_3_text, 464: meds_cur_7_text, 484: why_tx_6_text, 485: why_tx_8_text, 486: why_tx_12_text, 522: inf_7_text, 555: ins_ina_8_text, 589: wcs_1_o, 610: eat_change_how_2, 617: eat_change_how_9, 622: eat_change_how_14, 623: eat_change_how_15, 632: eat_change_env_how3, 636: eat_change_env_how7, 637: eat_change_env_how8, 674: sa_occur_loc6, 686: sa_loc_campbldg, 688: sa_loc_offnonres, 689: sa_loc_frat, 691: sa_loc_dk, 692: sa_loc_oth_text, 694: sa_who_fam, 697: sa_who_empl, 702: sa_who_part, 704: sa_who_oth, 707: sa_who_woman, 708: sa_who_transm, 709: sa_who_transw, 710: sa_who_queer, 711: sa_who_genoth, 712: sa_who_dk, 714: sa_tell_1, 718: sa_tell_5, 720: sa_tell_7, 721: sa_tell_8, 722: sa_tell_9, 724: sa_tell_11, 725: sa_tell_13, 726: sa_tell_14, 727: sa_tell_12, 729: sa_nodiscl_1, 730: sa_nodiscl_2, 731: sa_nodiscl_3, 732: sa_nodiscl_4, 733: sa_nodiscl_5, 734: sa_nodiscl_6, 735: sa_nodiscl_7, 736: sa_nodiscl_8, 737: sa_nodiscl_9, 738: sa_nodiscl_10, 739: sa_nodiscl_11, 740: sa_nodiscl_12, 741: sa_nodiscl_13, 742: sa_nodiscl_14, 744: sa_nodiscl_16, 745: sa_nodiscl_17, 746: sa_nodiscl_18, 747: sa_nodiscl_19, 748: sa_nodiscl_20, 749: sa_nodiscl_21, 750: sa_nodiscl_22, 751: sa_nodiscl_23, 752: sa_nodiscl_24, 755: sa_sch_help, 762: dx_chronic_arth, 763: dx_chronic_sca, 765: dx_chronic_canc, 767: dx_chronic_hiv, 772: dx_chronic_auto_text, 773: dx_chronic_other_text, 776: exerc_changed_how_text, 790: conc_oth, 806: birthcontrol_4, 807: birthcontrol_5, 808: birthcontrol_6, 809: birthcontrol_7, 811: birthcontrol_9, 814: birthcontrol_12, 815: birthcontrol_10_text, 820: preg_dk, 879: infoseek_oth_text, 890: witness_6_text, 901: inter_y_6, 910: inter_n_6, 922: inter_n_why_9_text, 979: hostcli_other_text, 1009: excl_pers_other_text, 1046: campus_oth, 1084: persist_challenge_1, 1088: persist_challenge_5, 1092: persist_challenge_9, 1093: persist_challenge_10, 1095: persist_challenge_11_text, 1126: aca_dep_7, 1129: aca_eat_3, 1130: aca_eat_4, 1132: aca_eat_6, 1133: aca_eat_7, 1139: aca_add_6, 1140: aca_add_7, 1143: aca_substance_3, 1144: aca_substance_4, 1145: aca_substance_5, 1146: aca_substance_6, 1147: aca_substance_7, 1157: aca_phys_assault_3, 1158: aca_phys_assault_4, 1159: aca_phys_assault_5, 1160: aca_phys_assault_6, 1161: aca_phys_assault_7, 1164: aca_sex_assault_3, 1165: aca_sex_assault_4, 1166: aca_sex_assault_5, 1167: aca_sex_assault_6, 1168: aca_sex_assault_7, 1172: afford_school, 1173: afford_food, 1174: afford_transp, 1175: afford_cc, 1176: afford_hc, 1177: afford_books, 1178: afford_house, 1197: peer3_5, 1198: peer3_6, 1200: peer4_1, 1201: peer4_2, 1202: peer4_3, 1203: peer4_4, 1204: peer4_5, 1205: peer4_6, 1208: peer5_2, 1209: peer5_3, 1212: peer5_6, 1223: peer10_1, 1224: peer10_2, 1225: peer10_3, 1226: peer10_4, 1227: peer10_5, 1228: peer10_6, 1230: peer11_1, 1231: peer11_2, 1232: peer11_3, 1233: peer11_4, 1238: peer13_1, 1239: peer13_2, 1240: peer13_3, 1241: peer13_4, 1242: peer14_1, 1243: peer14_2, 1244: peer14_3, 1245: peer14_4, 1246: peer15_1, 1247: peer15_2, 1248: peer15_3, 1249: peer15_4, 1250: peer16_1, 1251: peer16_2, 1252: peer16_3, 1253: peer16_4, 1254: peer16_5, 1255: peer16_6, 1261: peer18_1, 1262: peer18_2, 1263: peer18_3, 1264: peer18_4, 1277: peer22_1, 1278: peer22_2, 1280: peer22_4, 1285: peer23_2, 1288: peer23_5, 1290: peer23_6_text, 1293: peer24_3, 1295: peer24_5, 1296: peer24_6, 1297: peer24_7, 1398: ab_emo_par, 1403: ab_emo_train, 1404: ab_emo_med, 1405: ab_emo_oth, 1409: ab_emo_aca, 1411: ab_emo_othcont, 1413: ab_phys_par, 1414: ab_phys_rm, 1416: ab_phys_coach, 1417: ab_phys_tm, 1418: ab_phys_train, 1421: ab_phys_oth_text, 1422: exp_conc_head, 1423: exp_conc_vert, 1424: exp_conc_naus, 1425: exp_conc_fati, 1426: exp_conc_light, 1428: exp_conc_anx, 1429: exp_conc_anger, 1430: exp_conc_attn, 1431: exp_conc_memory, 1432: exp_conc_blur, 1468: substanceuse, 1469: ebi, 1470: sexualassault, 1471: overallhealth, 1473: finstress, 1476: retention, 1479: studathlete, 1481: peer, 1485: drug_her, 1488: drug_met, 1495: drug_ath, 1497: drug_other_text, 1522: diet_veg_weight, 1525: diet_veg_other, 1577: pfdrug_steroid, 1578: pfdrug_muscle, 1594: field_elec, 1595: field_weld, 1596: field_auto, 1597: field_hvac, 1599: field_cul, 1601: field_crim, 1604: field_comp, 1607: degree_other_tech, 1609: field_other_tech_text) have mixed types. Specify dtype option on import or set low_memory=False.
  hms_23 = pd.read_csv("../data/raw/2022-2023/HMS_2022-2023_PUBLIC_instchars.csv")

In [42]:
# 2023-2024
hms_24 = pd.read_csv("../data/raw/2023-2024/HMS_2023-2024_PUBLIC_instchars.csv")

C:\Users\noahh\AppData\Local\Temp\ipykernel_13300\2315900744.py:2: DtypeWarning: Columns (12: gender_text, 23: sexual_text, 38: black_other_text, 44: asian_other_text, 51: his_other_text, 64: st_otherdoc_text, 109: covid_clsformat_text, 113: enroll_text, 161: field_other_tech_text, 170: living_sit_text, 234: sib_other_text, 300: internet_3_8_TEXT, 348: dx_bip_4_text, 356: dx_ax_6_text, 364: dx_ocd_6_text, 370: dx_trauma_4_text, 376: dx_neurodev_4_text, 384: dx_ea_6_text, 392: dx_psy_6_text, 405: dx_perso_11_text, 410: dx_sa_2_text, 523: stim_reason_TEXT, 529: antianx_reason_TEXT, 536: meds_w_3_text, 540: stim_prescriber_7_TEXT, 571: why_tx_8_text, 608: inf_7_text, 641: ins_ina_8_text, 688: infoseek_oth_text, 699: witness_6_text, 712: inter_y_6_text, 721: inter_n_6_text, 731: inter_n_why_9_text, 790: drug_other_text, 872: ab_emo_othcont_text, 940: hostcli_other_text, 970: excl_pers_other_text, 999: campus_oth_text, 1064: sa_occur_loc6_text, 1081: sa_loc_oth_text, 1094: sa_who_oth_text, 1109: sa_tell_12_text, 1134: sa_nodiscl_24_text, 1147: Peer3_5_TEXT, 1154: Peer4_6_TEXT, 1162: Peer5_6_TEXT, 1164: Peer6_3_TEXT, 1231: Peer22_5_TEXT, 1238: Peer23_6_TEXT, 1248: Peer25_3_TEXT, 1249: Peer, 1314: eat_change_how_15_text, 1328: eat_change_env_how8_text, 1342: diet_veg_other_text, 1350: exerc_changed_how_text, 1375: birthcontrol_10_text, 1435: persist_challenge_11_text, 1437: highestdeg_text, 1526: hous_conc_5_text, 1538: schol_other_text) have mixed types. Specify dtype option on import or set low_memory=False.
  hms_24 = pd.read_csv("../data/raw/2023-2024/HMS_2023-2024_PUBLIC_instchars.csv")

In [43]:
# 2024-2025
hms_25 = pd.read_csv("../data/raw/2024-2025/HMS_2024-2025_PUBLIC_instchars.csv")

C:\Users\noahh\AppData\Local\Temp\ipykernel_13300\1171019825.py:2: DtypeWarning: Columns (13: gender_text, 25: sexual_text, 53: state_9thgrade, 54: state_10thgrade, 55: state_11thgrade, 56: state_12thgrade, 57: year_9thgrade, 58: year_10thgrade, 59: year_11thgrade, 60: year_12thgrade, 881: Grad, 1475: Peer, 1590: StartDate2) have mixed types. Specify dtype option on import or set low_memory=False.
  hms_25 = pd.read_csv("../data/raw/2024-2025/HMS_2024-2025_PUBLIC_instchars.csv")

In [44]:
# 2025-2026
hms_26 = pd.read_csv("../data/raw/2025-2026/HMS_2025-2026_PUBLIC_instchars.csv")

C:\Users\noahh\AppData\Local\Temp\ipykernel_13300\4153514391.py:2: DtypeWarning: Columns (12: gender_text, 24: sexual_text, 55: race_other_text, 61: black_other_text, 67: asian_other_text, 74: his_other_text, 81: pi_other_text, 85: residenc_text, 87: living_sit_text, 115: clsformat_text, 131: degree_other_tech, 135: enroll_text, 157: field_other_text, 184: field_other_tech_text, 255: sib_other_text, 318: recovery_path_text, 328: recovery_service_text, 337: recovery_aware_text, 359: dx_dep_4_text, 365: dx_bip_4_text, 373: dx_ax_6_text, 381: dx_ocd_6_text, 387: dx_trauma_4_text, 393: dx_neurodev_4_text, 401: dx_ea_6_text, 409: dx_psy_6_text, 422: dx_perso_11_text, 427: dx_sa_2_text, 444: ADHD2_4_TEXT, 446: ADHD3_text, 463: A988_followup_text, 465: A988_reason_text, 478: talk1_8_text, 502: ADHD_therapy_loc_text, 575: stim_reason_TEXT, 581: antianx_reason_TEXT, 588: meds_w_3_text, 601: ADHD_meds_text, 622: why_tx_6_text, 623: why_tx_8_text, 624: why_tx_12_text, 663: inf_7_text, 696: ins_ina_8_text, 701: suicide_4_6_TEXT, 744: persist_challenge_11_text, 746: highestdeg_text, 819: SubstanceUse, 820: EBI, 821: SexualAssault, 822: OverallHealth, 823: KnowAtt, 824: FinStress, 825: UpBy, 826: Coping, 827: Retention, 828: Climate, 829: CCC, 830: StudAthlete, 831: Policing, 832: UNCF, 834: RacialTrauma, 835: AI, 836: Grad, 967: nicotine_quit_text, 1031: infoseek_oth_text, 1072: inter_n_why_9_text, 1115: GSM_3_8_TEXT, 1214: AI_4_10_TEXT, 1307: hostcli_other_text, 1338: excl_pers_other_text, 1414: sa_occur_loc6_text, 1494: exerc_changed_how_text, 1519: birthcontrol_10_text, 1534: STIprev_5_text, 1554: Peer3_5_TEXT, 1561: Peer4_6_TEXT, 1569: Peer5_6_TEXT, 1571: Peer6_3_TEXT, 1587: Peer10_6_TEXT, 1625: Peer16_6_TEXT, 1661: Peer22_5_TEXT, 1668: Peer23_6_TEXT, 1676: Peer24_6_TEXT, 1678: Peer25_3_TEXT, 1679: Peer, 1683: living_sit_fin_text, 1707: hous_conc_5_text, 1713: payeduc_other_text, 1722: schol_other_text, 1770: eat_change_how_15_text, 1809: inst_msi_type) have mixed types. Specify dtype option on import or set low_memory=False.
  hms_26 = pd.read_csv("../data/raw/2025-2026/HMS_2025-2026_PUBLIC_instchars.csv")

In [45]:
# selected variables

selected_vars = [
    # Outcomes
    "flourish",
    "deprawsc",
    "anx_score",

    # Main factors
    "fincur",
    "finpast",
    "belong1",
    "discrim_race",
    "discrim_culture",
    "discrim_gender",
    "discrim_sexual",
    "alc_any",

    # Controls
    "age",
    "international",
    "educ_par1",
    "educ_par2",
    "enroll",

    # Survey weight
    "nrweight"]

In [ ]:
# create copies of data
hms_23_selected = hms_23[selected_vars].copy()
hms_24_selected = hms_24[selected_vars].copy()
hms_25_selected = hms_25[selected_vars].copy()
hms_26_selected = hms_26[selected_vars].copy()

In [47]:
# create year columns
hms_23_selected["survey_year"] = "2022-2023"
hms_24_selected["survey_year"] = "2023-2024"
hms_25_selected["survey_year"] = "2024-2025"
hms_26_selected["survey_year"] = "2025-2026"

In [57]:
# Join the tables together

hms_all = pd.concat([hms_23_selected, hms_24_selected, hms_25_selected, hms_26_selected],
                    ignore_index = True)
hms_all.head()

,flourish,deprawsc,anx_score,fincur,finpast,belong1,discrim_race,discrim_culture,discrim_gender,discrim_sexual,alc_any,age,international,educ_par1,educ_par2,enroll,nrweight,survey_year
0,45.0,9.0,13.0,2.0,3.0,3.0,0.0,0.0,0.0,0.0,1.0,21.0,0.0,5.0,3.0,1.0,3.662791,2022-2023
1,NaN,NaN,NaN,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,21.0,0.0,4.0,3.0,1.0,5.362319,2022-2023
2,51.0,2.0,2.0,4.0,5.0,6.0,0.0,0.0,0.0,0.0,1.0,41.0,0.0,6.0,5.0,2.0,3.662791,2022-2023
3,50.0,6.0,3.0,3.0,4.0,3.0,0.0,0.0,0.0,0.0,1.0,24.0,0.0,4.0,3.0,1.0,5.362319,2022-2023
4,55.0,3.0,NaN,2.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,27.0,0.0,3.0,5.0,1.0,3.662791,2022-2023

In [58]:
# shape
hms_all.shape

(333347, 18)

In [59]:
# check how many per year
hms_all["survey_year"].value_counts()

survey_year
2023-2024    104729
2024-2025     84735
2022-2023     76406
2025-2026     67477
Name: count, dtype: int64

In [60]:
# info
hms_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 333347 entries, 0 to 333346
Data columns (total 18 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   flourish         302632 non-null  float64
 1   deprawsc         295689 non-null  float64
 2   anx_score        294916 non-null  float64
 3   fincur           322082 non-null  float64
 4   finpast          321710 non-null  float64
 5   belong1          314931 non-null  float64
 6   discrim_race     310647 non-null  float64
 7   discrim_culture  310250 non-null  float64
 8   discrim_gender   309727 non-null  float64
 9   discrim_sexual   309578 non-null  float64
 10  alc_any          296716 non-null  float64
 11  age              333347 non-null  float64
 12  international    328803 non-null  float64
 13  educ_par1        320653 non-null  float64
 14  educ_par2        315405 non-null  float64
 15  enroll           316938 non-null  float64
 16  nrweight         333347 non-null  float64
 17  survey_year      333347 non-null  str
dtypes: float64(17), str(1)
memory usage: 45.8 MB

In [61]:
# summaries
hms_all.describe()

,flourish,deprawsc,anx_score,fincur,finpast,belong1,discrim_race,discrim_culture,discrim_gender,discrim_sexual,alc_any,age,international,educ_par1,educ_par2,enroll,nrweight
count,302632.000000,295689.000000,294916.000000,322082.000000,321710.000000,314931.000000,310647.000000,310250.000000,309727.000000,309578.000000,296716.000000,333347.000000,328803.000000,320653.000000,315405.000000,316938.000000,333347.000000
mean,43.593182,8.496654,7.689793,2.746406,3.143632,2.920198,0.061481,0.054775,0.090383,0.037038,0.453420,23.590323,0.076182,5.062710,4.941551,1.142413,1.734507
std,8.943413,6.269181,5.826097,1.118866,1.253971,1.354833,0.240212,0.227541,0.286730,0.188854,0.497826,7.677082,0.265290,1.818527,1.871557,0.376749,2.592178
min,8.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,0.000000,1.000000,1.000000,1.000000,0.142613
25%,39.000000,4.000000,3.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,19.000000,0.000000,4.000000,3.000000,1.000000,0.631376
50%,46.000000,7.000000,7.000000,3.000000,3.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,21.000000,0.000000,6.000000,6.000000,1.000000,1.077505
75%,50.000000,12.000000,12.000000,3.000000,4.000000,4.000000,0.000000,0.000000,0.000000,0.000000,1.000000,25.000000,0.000000,7.000000,6.000000,1.000000,1.970260
max,56.000000,27.000000,21.000000,5.000000,5.000000,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,120.000000,1.000000,8.000000,8.000000,3.000000,277.500000

In [62]:
# NA values
hms_all.isna().sum()

flourish           30715
deprawsc           37658
anx_score          38431
fincur             11265
finpast            11637
belong1            18416
discrim_race       22700
discrim_culture    23097
discrim_gender     23620
discrim_sexual     23769
alc_any            36631
age                    0
international       4544
educ_par1          12694
educ_par2          17942
enroll             16409
nrweight               0
survey_year            0
dtype: int64

In [ ]:
# percentage of missingness per column
missing_summary = pd.DataFrame({
    "missing_count": hms_all.isna().sum(),
    "missing_percent": hms_all.isna().mean() * 100
})

missing_summary.sort_values("missing_percent", ascending=False)

                 missing_count  missing_percent
anx_score                38431        11.528827
deprawsc                 37658        11.296937
alc_any                  36631        10.988849
flourish                 30715         9.214122
discrim_sexual           23769         7.130408
discrim_gender           23620         7.085709
discrim_culture          23097         6.928816
discrim_race             22700         6.809721
belong1                  18416         5.524573
educ_par2                17942         5.382379
enroll                   16409         4.922498
educ_par1                12694         3.808044
finpast                  11637         3.490957
fincur                   11265         3.379361
international             4544         1.363144
age                          0         0.000000
nrweight                     0         0.000000
survey_year                  0         0.000000